kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.26
    commands:
      - go build ./...
      - go vet ./...
      - go test -v -cover -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... -race ./...

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
